Update schema-backup

diff --git a/schema-backup b/schema-backup
--- a/schema-backup
+++ b/schema-backup
@@ -109,3 +109,52 @@ echo "Completion Time: $end_time" >> "$log_location"
 # Display the log file path
 echo "Backup and restore completed. Log file: $log_location"
 
+------------------------------------------------------------------------------------------------------------------------------------
+
+#!/bin/bash
+
+# Source the environment file
+source /opt/app/localhome/postgres/pg_env.sh
+
+# Specify backup and log file locations
+backup_location="/opt/backup"
+log_location="/opt/backup/schemabackup_restore_log.txt"
+original_schema="schema"  # Replace with your original schema name
+new_schema="newmepstg"    # Replace with your desired new schema name
+
+# Record the start time
+start_time=$(date +"%Y-%m-%d %H:%M:%S")
+
+# Backup the schema to /opt/backup
+pg_dump -h localhost -U deployadmin -d citus -n mepstg --schema="$original_schema" > "$backup_location/mepstg_schema_backup.sql"
+
+# Replace the original schema name with the new schema name in the SQL file
+sed -i "s/$original_schema/$new_schema/g" "$backup_location/mepstg_schema_backup.sql"
+
+# Drop target schema if already exists
+psql -h localhost -U deployadmin -d citus -c "DROP SCHEMA IF EXISTS $new_schema CASCADE;"
+
+# Create the target schema
+psql -h localhost -U deployadmin -d citus -c "CREATE SCHEMA IF NOT EXISTS $new_schema;"
+
+# Restore the schema within the same database using psql
+psql -h localhost -U deployadmin -d citus -f "$backup_location/mepstg_schema_backup.sql"
+
+# Check the status of the restore operation
+if [ $? -eq 0 ]; then
+  echo "Restore completed successfully."
+else
+  echo "Error: Restore operation failed."
+fi
+
+# Record the completion time
+end_time=$(date +"%Y-%m-%d %H:%M:%S")
+
+# Output the start and completion times to a log file
+echo "Start Time: $start_time" > "$log_location"
+echo "Completion Time: $end_time" >> "$log_location"
+
+# Display the log file path
+echo "Backup and restore completed. Log file: $log_location"
+
+
