Update schema-backup

diff --git a/schema-backup b/schema-backup
--- a/schema-backup
+++ b/schema-backup
@@ -320,4 +320,40 @@ echo "Completion Time: $end_time" >> "$log_location"
 echo "Backup completed. Log file: $log_location"
 
 
+-----------------------------------------------------------------------------------------------------------------------------------------
+
+#!/bin/bash
+
+# Source the environment file
+source /opt/app/localhome/postgres/pg_env.sh
+
+# Specify backup and log file locations
+backup_location="/opt/backup"
+log_location="/opt/backup/schemabackup_log.txt"
+original_schema="schema"  # Replace with your desired schema name
+parallelism_dump=4        # Set the desired level of parallelism for pg_dump
+
+# Record the start time
+start_time=$(date +"%Y%m%d%H%M%S")
+backup_dir="$backup_location/mepstg_schema_backup_$start_time"
+
+# Backup the schema with parallelism using directory format
 pg_dump -h localhost -U deployadmin -d citus -n "$original_schema" --schema="$original_schema" -j "$parallelism_dump" -F d -f "$backup_dir"
+
+# Check the status of the backup operation
+if [ $? -eq 0 ]; then
+  echo "Backup completed successfully."
+else
+  echo "Error: Backup operation failed."
+fi
+
+# Record the completion time
+end_time=$(date +"%Y-%m-%d %H:%M:%S")
+
+# Output the start and completion times to a log file
+echo "Start Time: $start_time" > "$log_location"
+echo "Completion Time: $end_time" >> "$log_location"
+
+# Display the log file path
+echo "Backup completed. Log file: $log_location"
+
