Update schema-backup

diff --git a/schema-backup b/schema-backup
--- a/schema-backup
+++ b/schema-backup
@@ -282,3 +282,49 @@ echo "Completion Time: $end_time" >> "$log_location"
 
 # Display the log file path
 echo "Backup and restore completed. Log file: $log_location"
+
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
+
+#!/bin/bash
+
+# Source the environment file
+source /opt/app/localhome/postgres/pg_env.sh
+
+# Specify backup and log file locations
+backup_location="/opt/backup"
+log_location="/opt/backup/backup_restore_log.txt"
+original_schema="mepstg"  # Replace with your original schema name
+new_schema="testmepstg"    # Replace with your desired new schema name
+
+# Record the start time
+start_time=$(date +"%Y-%m-%d %H:%M:%S")
+
+# Backup the schema to /opt/backup in .dump format
+pg_dump -h localhost -U deployadmin -d citus -n mepstg --format=c --file="$backup_location/mepstg_backup.dump" --schema="$original_schema"
+
+# Drop target schema if already exists
+psql -h localhost -U deployadmin -d citus -c "DROP SCHEMA IF EXISTS $new_schema CASCADE;"
+
+# Create the target schema
+psql -h localhost -U deployadmin -d citus -c "CREATE SCHEMA IF NOT EXISTS $new_schema;"
+
+# Restore the schema using pg_restore with schema mapping
+pg_restore -h localhost -U deployadmin -d citus --schema="$new_schema" --no-password --single-transaction "$backup_location/mepstg_backup.dump"
+
+# Check the status of the restore operation
+if [ $? -eq 0 ]; then
+  echo "Restore completed successfully."
+else
+  echo "Error: Restore operation failed."
+fi
+
+# Record the completion time
+end_time=$(date +"%Y-%m-%d %H:%M:%S")
+
+# Output the start and completion times to a log file
+echo "Start Time: $start_time" > "$log_location"
+echo "Completion Time: $end_time" >> "$log_location"
+
+# Display the log file path
+echo "Backup and restore completed. Log file: $log_location"
+
