Update schema-backup

diff --git a/schema-backup b/schema-backup
--- a/schema-backup
+++ b/schema-backup
@@ -140,7 +140,7 @@ echo "Completion Time: $end_time" >> "$log_location"
 echo "Backup completed. Log file: $log_location"
 
 ---------------------------------------------------------------------------------------------------------------------------------------------------
-The script bellow will create the schema with a new name
+The script bellow will create the schema with a new name by using sed command
 --------------------------------------------------------------------------------------------------------------
 
 #!/bin/bash
@@ -186,3 +186,52 @@ echo "Completion Time: $end_time" >> "$log_location"
 
 # Display the log file path
 echo "Restore completed. Log file: $log_location"
+
+--------------------------------------------------------------------------------------------------------------------------------------------------------------
+The bellow script will make renaming of schema/objects fatster by using awk command , good for bigger backupfiles
+--------------------------------------------------------------------------------------------------------------------------------------------
+
+#!/bin/bash
+
+# Source the environment file
+source /opt/app/localhome/svcpostgres/pg_env.sh
+
+# Specify backup file location
+backup_location="/opt/backup"
+log_location="/opt/backup/restore_log.txt"
+original_schema="ngmep"  # Replace with your original schema name
+new_schema="newngmep"    # Replace with your desired new schema name
+
+# Record the start time
+start_time=$(date +"%Y-%m-%d %H:%M:%S")
+
+# Drop the target schema if it already exists
+psql -h localhost -U deployadmin -d citus -c "DROP SCHEMA IF EXISTS $new_schema CASCADE"
+
+# Create the target schema
+psql -h localhost -U deployadmin -d citus -c "CREATE SCHEMA IF NOT EXISTS $new_schema;"
+
+# Replace the original schema name with the new schema name in the SQL file using awk
+backup_file="$backup_location/$original_schema"_backup.sql
+awk -v old="$original_schema" -v new="$new_schema" '{gsub(old, new)}1' "$backup_file" > "$backup_file.tmp" && mv "$backup_file.tmp" "$backup_file"
+
+# Restore the schema using psql with a new schema name
+psql -h localhost -U deployadmin -d citus -f "$backup_file" -v new_schema="$new_schema"
+
+# Check the status of the restore operation
+if [ $? -eq 0 ]; then
+  echo "Restore completed successfully."
+else
+  echo "Error: Restore operation failed."
+fi
+
+# Record the completion time
+end_time=$(date +"%Y-%m-%d %H:%M:%S")
+
+# Output the start and completion times to the log file
+echo "Start Time: $start_time" > "$log_location"
+echo "Completion Time: $end_time" >> "$log_location"
+
+# Display the log file path
+echo "Restore completed. Log file: $log_location"
+
